name: Deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: up9cloud/action-rsync@v1.3
        env:
          HOST: 185.232.14.23
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /home/u339727842/public_html/catbot
          MODE: push
          VERBOSE: true
          PORT: 65002
          USER: u339727842
          ARGS: -avz --exclude-from=.gitignore --exclude=/.git/ --exclude=/.github/
          POST_SCRIPT: pwd && composer install -n
